version: '3.9'
services:
  postgres:
    container_name: postgres1
    image: postgres:16
    hostname: database
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=attackdefencedb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5430:5432"

  webapi:
    image: docker.io/${DOCKER_USERNAME}/webapi:latest
    hostname: webapi
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/attackdefencedb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  pgdata: