version: '3.9'

services:
  postgres:
    container_name: postgres1
    image: postgres:16
    hostname: database
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=attackdefencedb
      - POSTGRES_USER=${POSTGRES_USER:-attackdefencedb}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-attackdefencedb}
    networks:
      - app-net

  webapi:
    image: docker.io/${DOCKER_USERNAME}/webapi:latest
    container_name: webapi
    hostname: webapi
    expose:
      - "8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/attackdefencedb
      - POSTGRES_USER=${POSTGRES_USER:-attackdefencedb}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-attackdefencedb}
    networks:
      - app-net

  nginx:
    image: nginx:latest
    container_name: reverse_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./main.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - webapi
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
    name: app-net
    driver: bridge
