spring:
  application:
    name: attack-defence-platform
  config:
    import: optional:file:attack-defence-platform/.env[.properties]
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5430/attackdefencedb
    username: ${POSTGRES_USER:attackdefencedb}
    password: ${POSTGRES_PASSWORD:attackdefencedb}
  flyway:
    enabled: true
    locations:
      - migration
  data:
    redis:
      host: redis
      port: 6379
      database: 0
      timeout: 2000
springdoc:
  swagger-ui:
    enabled: true
logging:
  level:
    org.springframework.web.socket.config.WebSocketMessageBrokerStats: WARN

competition:
  defaults:
    totalRounds: 100
    roundDurationMinutes: 3
    flagSendCost: 300
    flagLostCost: 150
  scoring:
    alpha: 0.05
    gamma: 1.0
checkers:
  directory: /var/lib/checkers/

jwt:
  secret: ${JWT_SECRET:r1Wq3Y7Ql8ivrpC4A6vEgBg1kllCKCrFkwhbZUNZ6Y8=}
  access:
    lifetime: 60m
  refresh:
    lifetime: 1d

github:
  token: ${REPO_TOKEN}
  organization: AttackDefenseHITs