export const API_URLS = {
    // BASE: 'http://46.29.239.208:8080/api/',
    // BASE_WS: 'ws://46.29.239.208:8080/ws',
    BASE: 'https://hits-ad.ru/api/',
    BASE_WS: 'wss://hits-ad.ru/ws',
    // BASE: 'http://localhost:8080/api/',
    // BASE_WS: 'ws://localhost:8080/ws',
    REFRESH_TOKEN: 'token/refresh',
    LOGIN: 'auth/login',
    REGISTRATION: 'auth/register',
    PROFILE: 'users/profile',
    TEAM: 'team',
    TEAM_MEMBERS_RATING: 'team/members-rating',
    ROLE: 'users/role',
    TEAMS_DASHBOARD: 'dashboard',
    VM: 'admin/vms',
    COMPETITION: 'competition',
    SERVICES: 'admin/services',
    DEPLOY: 'admin/deploy',
    CHECKERS: 'checkers',
    STATUSES: 'statuses',
    SEND_FLAG: 'flags/send',
    ADMIN_HINTS: 'admin/hints',
    HINTS: 'hints',
    ADMIN_REPO: 'admin/repo',
}