CREATE TABLE users (
      id UUID PRIMARY KEY,
      login VARCHAR(255) UNIQUE NOT NULL,
      name VARCHAR(255) NOT NULL,
      registration_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      password VARCHAR(255) NOT NULL,
      role VARCHAR(50) NOT NULL
);
