name: Deploy Attack-Defense

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_KEY }}

      - name: Build Docker image
        run: |
          docker build -t attackdefense/webapi:latest .

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to registry
        run: |
          docker tag attackdefense/webapi:latest docker.io/${{ secrets.DOCKER_USERNAME }}/webapi:latest
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/webapi:latest

      - name: Add VPS to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          ssh -t $VPS_USER@$VPS_HOST << 'EOF'
            docker pull docker.io/${{ secrets.DOCKER_USERNAME }}/webapi:latest
            docker stop webapi || true
            docker rm webapi || true
            docker run -d --name webapi -p 8080:8080 \
              -e SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/attackdefensedb \
              -e POSTGRES_USER=${POSTGRES_USER} \
              -e POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
              docker.io/${{ secrets.DOCKER_USERNAME }}/webapi:latest
          EOF
      
